- name: Install NodeJS
  ansible.builtin.import_playbook: nodejs.yaml
    

- name: Set-up Application
  ansible.builtin.import_playbook:
    name: common
    tasks_from: app-setup

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: Load-schema
  ansible.builtin.import_playbook:
    name: common
    tasks_from: load_mongo_schema

- name: systemd service
  ansible.builtin.import_playbook:
    name: common
    tasks_from: systemd-service