- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.yum:
    name: mongodb-mongosh
    state: present

- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.featureit.online < /app/schema/catalogue.js
  register: products_count # keep double quotes
