- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.yum:
    name: mongodb-mongosh
    state: present

- name: load catalogue data
  ansible.builtin.command: mongosh --host mongodb.featureit.online < /app/schema/catalogue.js
  when: product_count.stdout == "0" # keep double quotes
